Indexing and Slicing In Python using Numpy

In [1]:
import numpy as np

In [10]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [5]:
array_1d[0]

1

In [6]:
array_1d[1]

2

In [7]:
array_1d[-3]

4

In [8]:
array_2d

[[1, 2, 3], [4, 5, 6]]

In [11]:
array_2d[0,0]

1

In [12]:
array_2d[0,1]

2

In [14]:
array_2d[1,-1]

6

In [15]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
array_3d[0,1,2]

6

In [17]:
array_3d[1,1,-1]

12

In [18]:
array_1d

array([1, 2, 3, 4, 5, 6])

In [19]:
array_1d[1:]

array([2, 3, 4, 5, 6])

In [20]:
array_1d[3:5]

array([4, 5])

In [21]:
array_1d[-3:-1]

array([4, 5])

In [22]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
array_2d[1,1:]

array([5, 6])

In [24]:
array_2d[-2:-3:-1]

array([[1, 2, 3]])

In [25]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
array_3d[0,1:,1:]

array([[5, 6]])