Common Math and Stastical Fungtions in Numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([[4,3,2],[10,1,0],[5,8,24]])

In [3]:
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [4]:
np.amin(arr)

0

In [5]:
np.amin(arr,axis=0)

array([4, 1, 0])

In [6]:
np.amin(arr,axis=1)

array([2, 0, 5])

In [7]:
np.max(arr)

24

In [8]:
np.amax(arr,axis=0)

array([10,  8, 24])

In [9]:
np.median(arr)

4.0

In [10]:
np.std(arr)

6.944222218666553

In [11]:
np.var(arr)

48.22222222222222

In [12]:
np.percentile(arr,50)

4.0

In [13]:
deg = np.array([0,30,45,60,90])

In [15]:
np.sin(deg*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [16]:
np.cos(deg*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [17]:
np.tan(deg*np.pi/180)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [18]:
'''
arcsin
arccos
arctan
'''


'\narcsin\narccos\narctan\n'

In [21]:
arr = np.array([0.1,0.8,-2.2,-9.87])

In [22]:
np.floor(arr)

array([  0.,   0.,  -3., -10.])

In [23]:
np.ceil(arr)

array([ 1.,  1., -2., -9.])