Belajar Numpy

In [1]:
import numpy as np

In [3]:
first_numpy_array = np.array([1,2,3,4])

In [5]:
print (first_numpy_array)

[1 2 3 4]


Array with zeeroes

In [6]:
array_with_zeros = np.zeros([2,3])
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

Array with ones

In [7]:
array_with_ones = np.ones([3,2])
array_with_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Array with empty

In [10]:
array_with_empty = np.empty((2,3))
array_with_empty

array([[1., 1., 1.],
       [1., 1., 1.]])

Array with arrange methode

In [11]:
np_arange = np.arange(10)

In [13]:
print (np_arange)

[0 1 2 3 4 5 6 7 8 9]


Reshape methode to change/create array

In [19]:
np_arange.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Linespace for linearly (equal) spaced data elements

In [20]:
np_linspace = np.linspace(1,6,5)

In [21]:
print (np_linspace)

[1.   2.25 3.5  4.75 6.  ]


One Dimensional Array

In [22]:
oneD_array = np.arange(12)

In [23]:
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


Two Dimensional Array

In [26]:
TwoD_array = oneD_array.reshape(3,4)
print(TwoD_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Three Dimensional Array

In [28]:
ThreeD_array = np.arange(27).reshape(3,3,3)
print (ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
