In [1]:
import numpy as np

In [2]:
np.array(24)

array(24)

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
np.array([[1,1,1],[1,2,1]])

array([[1, 1, 1],
       [1, 2, 1]])

In [9]:
np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [10]:
numpy_arr = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

In [11]:
numpy_arr.shape

(2, 2, 3)

In [12]:
numpy_arr.ndim

3

In [2]:
import numpy as np
numpy_arr = np.array([x for x in range(1,10)])

In [3]:
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
numpy_arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
numpy_arr = np.array([x for x in range(1,13)])

In [6]:
numpy_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
numpy_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [8]:
numpy_arr.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
numpy_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])